### PR TITLE
Remove the deprecated portageq usage

### LINKED ISSUE #19: `qubes-core-qrexec-4.1.32` build fails in qubes 4.1 with "portageq is not allowed in ebuild scope"
sorry if you're already tracking this. probably related: https://bugs.gentoo.org/916296

```
>>> Preparing source in /var/tmp/portage/app-emulation/qubes-core-qrexec-4.1.23/work/qubes-core-qrexec-4.1.23 ...
 * ERROR: app-emulation/qubes-core-qrexec-4.1.23::qubes failed (prepare phase):
 *   portageq is not allowed in ebuild scope
 * 
 * Call stack:
 *          ebuild.sh, line  136:  Called src_prepare
 *        environment, line 4555:  Called qubes_verify_sources_git 'v4.1.23'
 *        environment, line 4430:  Called portageq 'get_repo_path' '/' 'qubes'
 *   phase-helpers.sh, line 1010:  Called die
 * The specific snippet of code:
 *   	die "portageq is not allowed in ebuild scope"
 ```

you can work around this by replacing the `portageq` invocation in `eclass/qubes.eclass` with a hard-coded path to your qubes repo, but that's not ideal for a number of reasons (and the build still fails due to the `_FORTIFY_SOURCE` redefinition talked about in #12, which requires additional patching)

### PR DESCRIPTION
**Pull request by lubellier**
Fixes #19 
Uses the gentooLTO solution : https://github.com/InBetweenNames/gentooLTO/commit/21d2ba49bde2180972513b878b768c6e1bddaa7c

### CODE REVIEW

**Comment by fepitre** [comment]
Thank you.

**Comment by lubellier** [comment]
With the above merge, the emerge sync failed for the qubes repo:
```
>>> Syncing repository 'qubes' into '/var/db/repos/qubes'...
/usr/bin/git fetch origin --depth 1 release4.1
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 2), reused 4 (delta 2), pack-reused 0
Unpacking objects: 100% (4/4), 1.11 KiB | 126.00 KiB/s, done.
From https://github.com/fepitre/qubes-gentoo
 * branch            release4.1 -> FETCH_HEAD
 + 04dd518...35fb64d release4.1 -> origin/release4.1  (forced update)
 * Using keys from /usr/share/openpgp-keys/9FA64B92F95E706BF28E2CA6484010B5CDC576E2.asc
 * Key refresh is disabled via a repos.conf sync-openpgp-key-refresh
 * setting, and this is a security vulnerability because it prevents
 * detection of revoked keys!
 * No valid signature found: unable to verify signature (missing key?)

Action: sync for repo: gentoo, returned code = 0
Action: sync for repo: qubes, returned code = 1
```

If I update in the `/etc/portage/repos.conf/qubes.conf` file with the  `sync-openpgp-key-refresh` option from _false_ to _true_, I get : 
```
>>> Syncing repository 'qubes' into '/var/db/repos/qubes'...
/usr/bin/git fetch origin --depth 1 release4.1
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
From https://github.com/fepitre/qubes-gentoo
 * branch            release4.1 -> FETCH_HEAD
 * Using keys from /usr/share/openpgp-keys/9FA64B92F95E706BF28E2CA6484010B5CDC576E2.asc
 * Refreshing keys via WKD ...                                                                                                                                               [ !! ]
 * Refreshing keys from keyserver ...!!! Verification impossible due to keyring problem:
OpenPGP keyring refresh failed:
gpg: refreshing 1 key from hkps://keyserver.ubuntu.com
gpg: keyserver refresh failed: Try again later


Action: sync for repo: gentoo, returned code = 0
Action: sync for repo: qubes, returned code = 1
```

Maybe a problem with my pgp key... But my key is available from the ubuntu keyserver : https://keyserver.ubuntu.com/pks/lookup?search=552BC8B26E38D080&fingerprint=on&op=index
What do you think about this?

**Comment by Tonux599** [comment]
The top most commit on the `release4.1` branch needs to be signed by @fepitre (which makes signing Manifests redundant, IMO).

**Comment by fepitre** [comment]
It should be improved to check signed tags instead of commits. It's not redundant because when we build template from our builder, we don't checkout without checking if there is at least a number of required signed tags. Having signed Manifest allows anyone adding this repository outside Qubes build workflow to check signature.

**Pull request merged**
