### PR TITLE
remove eutils dependency

### PR DESCRIPTION
**Pull request by ctr49**
It looks like all macros in ebuilds are still valid without eutils dependency and eutils is not supported for EAPI7 anymore (see #18).

This has been built an run-tested, but Manifest may need a refresh (or at least a pgp signature).

### CODE REVIEW

**Comment by fepitre** [comment]
Thank you for your pull request. I won't merge it right now until I find time to fix R4.2 branch first. For now, template in R4.2 builds fine but does not work. I hope to find time in the next two weeks.

**Comment by Tonux599** [comment]
@fepitre Any update on merging this? Right now as far as I can tell it's not possible to change any use flags on these packages as they report `(masked by: corruption)`.

I'm also getting some dependency issues with pandoc so went to enable the use flag `pandoc-bin` to try and resolve, but this issue is blocking that.

If that issue persists post merging of this PR, I'll open an issue.

**Comment by fepitre** [comment]
As of now, I cannot test it with R4.2 because template builds but does not work. I lake time to work on this subject. I need to figure out with @marmarek if I can focus on Gentoo and R4.2 for few days.

Sam 28 oct 2023, à 13:26, Thomas Clarke a écrit :

**Comment by colons** [comment]
i am a bit scared by the state of this. the production version of these packages have been broken for months, and they're not going to be fixed until the unreleased 4.2 versions are fixed. if one of these packages needs patching for security reasons, are users expected to upgrade to an unreleased version of qubes?

**Comment by marmarek** [comment]
Gentoo template is not officially supported, only community supported (see https://www.qubes-os.org/doc/templates/). Qubes core team do not guarantee updates (including security updates) for those templates, or even if they will work at all, it's all about community support and sometimes Frederic helping in his free time.

**Comment by Tonux599** [comment]
I have made a fork of this repo if anyone is interested. It will be primarily for personal use but others are free to use if it works for them. I've merged @ctr49's changes and updated the packages.

Interestingly, as far as I can tell authenticity is asserted by commit signing, not the clear-signed Manifest. Is this the case as far as you know @fepitre? If so, that would save time not having to sign each Manifest.

For anyone who wants to use it, place [my key](https://tonux.dev/E8ACBC6CFCCA7A99779FB69127B829528903C906.asc) in `/usr/share/openpgp-keys/E8ACBC6CFCCA7A99779FB69127B829528903C906.asc` and update the following in `/etc/portage/repos.conf/qubes.conf`

```
sync-uri = https://github.com/Tonux599/qubes-gentoo.git
sync-openpgp-key-path = /usr/share/openpgp-keys/E8ACBC6CFCCA7A99779FB69127B829528903C906.asc
```

I'll only be updating R4.1 for now, until I move to R4.2 or my repo becomes obsolete.

**Comment by fepitre** [comment]
Few updates, we have a working template for Gentoo 4.2 where I committed similar PR for release 4.2 (see `release4.2-staging`). I'm finishing few tests and we need to merge something in `core-qrexec` and `gui-agent` and we will be good. Sorry for the long time on this.

**Comment by edt11x** [comment]
Very nice @Tonux599 , that cleaned up my emerge. I have been just letting the Qubes packages fail, but it's so hard to see what else is wrong. Appreciate your efforts.

**Pull request merged**
